language: java
services:
- docker
if: tag IS present
cache:
  directories:
  - $HOME/.m2
before_install:
- echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin quay.io
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
- export current_tag=$(git describe --tags)
script: mvn package -B -Pbuild-image
deploy:
- provider: script
  script: docker push quay.io/hyperfoil/hyperfoil
  on:
    tags: true
- provider: releases
  api_key:
    secure: "i3JAJNEkOfr62rAJ/QG5hzyITfUhkWdR65XsINHMZ3UOF96kUFUoJscwsPoMBg8SQqLzKoNeHZ9LJTVEjwP8+sgrjnfuA+AjKa47HjPAaAfc0jgllx5CCbQEcOQdpuLyEMj0yoYPMfTn8zPfkBE16eZyTGc7jC1iQyQMVcHg1kZ6ls36UbQmnusbhBn5s/RnxuqjWrEwzCIZ1Pc6wxttfrEVltaw/ZuXgQf3ReJ0+JvlxCvhDiLg8yZjABf7LccjS6x9o+viUKmj9vKud2C4ZWlUOr7YhX+3dgolO7t23RaoSCWOSPy10CC2KajvzRjsXA7XjzVqjpQjJg+V/IpTfCFY+7DuDgbmlJRlyi1oMnFnub7EqCO4wnHbSvFre3ePk6sIod8X8WDqGDVlMzvYyIRo7cqtF0w/umR9y3Pke5XpTF1Zk+0Yd5COiVPCzn38ix+lkAR0CuamfErnHHoPfqt9+TGDMZeo/daDjEf7g7JhxN5J0jDI7ySCIDxHfYjnU1XKbHiZsHAy4jVp+9H88w2RYEyOkaOmGstaTqjvHJoyLnSR1esstdFslyFPq9VJtL5dlxdpyJW1IpgTzJCg4302bLsLDYTRM2A6jluZVl+dm65zxawwfuX36ySkHc3ieFwekMN7r3gnBePaOcgADrYImCwuth6vGb09FC8Pz1E="
  file: distribution/target/hyperfoil-$project_version.zip
  skip_cleanup: true
  on:
    tags: true
  name: $current_tag
