#!/bin/bash

echo "Running mvn formatter:format to ensure the code is properly formatted"

# running maven clean test
MVN_RESULT=$(mvn formatter:format impsort:sort 2>&1)
if [ $? -ne 0 ]; then
  echo
  echo "${MVN_RESULT}"
  echo
  echo "Error while formating the code"
  exit 1
fi

# add all modified files
git add -u

exit 0
