apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: controller
    namespace: hyperfoil
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - pods/status
    - pods/finalizer
    verbs:
    - "*"
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: controller
    namespace: hyperfoil
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hyperfoil
    name: hyperfoil
    namespace: hyperfoil
  spec:
    ports:
    - name: 8090-8090
      port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: hyperfoil
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: controller
    namespace: hyperfoil
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: controller
  subjects:
  - kind: ServiceAccount
    name: controller
    namespace: hyperfoil
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: hyperfoil
    name: controller
    namespace: hyperfoil
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: hyperfoil
      spec:
        containers:
        - command:
          - /deployment/bin/controller.sh
          - -Dio.hyperfoil.deploy.timeout=120000
          - -Dio.hyperfoil.deployer=k8s
          - -Dio.hyperfoil.controller.host=0.0.0.0
          image: quay.io/hyperfoil/hyperfoil:latest
          name: hyperfoil
        serviceAccountName: controller
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: hyperfoil
    name: hyperfoil
    namespace: hyperfoil
  spec:
    port:
      targetPort: 8090-8090
    to:
      kind: Service
      name: hyperfoil

